### ISSUE TITLE
python issue 

### ISSUE THREAD

**Issue by Ram-Nagar** [stevemussmann/admixturePipeline#11]
hi, 
I tried it running on a cluster computer but it throwing a python related error "ImportError: dynamic module does not define init function (PyInit_multiarray)"
Could you please help how to get over this error? 
I tried changing the path of the python3 but again it says that "bad interpreter: Permission denied"

Thanks

**Comment by stevemussmann** [comment]
It sounds like numpy is not installed, and possibly python3. Check with the administrator of your computer cluster to see if these are installed, and if so, how to access them.

**Comment by Ram-Nagar** [comment]
Both python3 and numpy are installed on the cluter and accessible to everyone. I run many other applications that need python3 and numpy on it. 
your scripts work well on my local computer but it gives "segmental fault" because of low RAM. 
Is it possible to make a conda environment for running your scripts

**Comment by stevemussmann** [comment]
Python3 and numpy may be installed, but the error messages you provided indicate they're not being found when you are attempting to run the program. You may want to double-check the path to Python that you changed in the scripts to make sure it is accurate, and perhaps work on troubleshooting this issue with your computer cluster's administrator. Without knowing how your computer cluster is configured, I'm very limited to the suggestions I can provide in this area. 

Unfortunately I don't have time to build a conda package right now (I'm in the middle of moving / starting a new job). I don't use conda, so I would have to learn it from scratch, and it might take me a couple of months to find time to do that.

If Docker is installed on your cluster, then you may try the Docker image that I created. 

Another option that I haven't tried - I've heard it's supposed to be easy to import Docker images to Singularity, if Singularity is installed on your cluster (I know a lot of computer clusters no longer use Docker itself due to security concerns). That might be an option to attempt, but I don't know anything about the process of actually accomplishing this.

**Comment by Ram-Nagar** [comment]
Thank Steve for this detailed reply.
I have managed to run but stuck a the last step.

while running the runEvalAdmix.py, I am getting the following error 

Traceback (most recent call last):
  File "/mnt/e/DATA_ANALYSIS/new_aus_isolates/final_pconting_varients/admixture_analysis/admixturePipeline_out/admixturePipeline_result/../../admixturePipeline/runEvalAdmix.py", line 24, in <module>
    main()
  File "/mnt/e/DATA_ANALYSIS/new_aus_isolates/final_pconting_varients/admixture_analysis/admixturePipeline_out/admixturePipeline_result/../../admixturePipeline/runEvalAdmix.py", line 17, in main
    ea = EvalAdmix(input.args.prefix, input.args.mc,input.args.evalAdmixRcode)
  File "/mnt/e/DATA_ANALYSIS/new_aus_isolates/final_pconting_varients/admixture_analysis/admixturePipeline/evaladmix.py", line 39, in __init__
    string = f.read()
  File "/home/ram_nipb/miniconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 40: invalid start byte
R[write to console]: Warning messages:

R[write to console]: 1:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library ‘/usr/local/lib/R/site-library’ contains no packages

R[write to console]: 2:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library ‘/usr/local/lib/R/site-library’ contains no packages

R[write to console]: 3:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library ‘/usr/local/lib/R/site-library’ contains no packages

Could help me understand what is it and how to get over it. 
Thnaks

**Comment by Ram-Nagar** [comment]
Can  you please also help me in interpreting this figure 
![image](https://user-images.githubusercontent.com/18412525/168235053-996bac5e-8dac-4ee3-b2de-3aabd236a2e6.png)

which is the best cluster and how to decide that.

Thanks

**Comment by stevemussmann** [comment]
For the error you received from runEvalAdmix - it looks like the error was thrown from the codecs.py library. I don't think I've tested this with Python 3.9, so I will have to look into that issue. That might take me a few weeks to find time to do it.

As for the figure - the lowest CV values indicate the best explanations of population structure. It looks like there's a lot of overlap in ranges in K =9 and K = 10. Possibly some lower values as well. You might have a complex situation of population structure in which there is hierarchical structure. In these cases I generally recommend reporting the barplots from multiple similarly-well supported K values (at least in supplemental material of a publication, if necessary).

**Comment by stevemussmann** [comment]
Apologies for the delay - I looked into the python error you were receiving regarding the codecs.py library but I could not replicate it. I have now tested the pipeline with Python versions up through 3.10.1 and was unable to replicate the issue. I think it may have been a system configuration issue with the machine you were using. I'm closing this for now, but please feel free to open a new issue if you run into other problems.
